- block:
    - name: Ensure python, pip and packages releated to ansible
      apt: name=python3-pip,libssl-dev,dbus

    - name: Ensure ansible and dependencies
      pip:
        name:
          - pip
          - python-apt
          - ansible==2.8.0
  tags:
    - ansible_dependencies

- name: 'Ensure useful packages'
  apt: name=tree,pv,vim,git,zsh,dnsutils,apt-file,ntp,locales

- name: 'Hostname'
  hostname: name="{{ hostname }}.{{ domain }}"
  tags:
    - hostname

- name: 'Hosts file'
  lineinfile: dest=/etc/hosts regexp='^127\.0\.1\.1\t.+' line='127.0.1.1\t{{ hostname }}.{{ domain }} {{ hostname }}'

- name: Ensure groups
  group: name="{{ item.name }}" gid="{{ item.gid }}"
  with_items: "{{ ubuntu_groups | default([]) }}"

- name: 'Ensure groups exist'
  group: name="{{ item.group }}" gid="{{ item.gid | default(omit) }}"
  when: item.group is defined and item.group is string
  with_items: "{{ users }}"

- name: 'Ensure groups with certain gid'
  group: name="{{ item.group.name }}" gid="{{ item.group.gid | default(omit) }}"
  when: item.group is defined and item.group is not string
  with_items: "{{ users }}"

- name: Ensure users
  user: name="{{ item.name }}" uid="{{ item.uid | default(omit) }}" home="{{ item.home | default(omit) }}" password="{{ item.password | default(omit) }}" group="{{ item.group | default(omit) }}" append=yes groups="{{ item.groups | default(omit) }}" createhome="yes" update_password=always shell="/bin/{{ item.shell | default('bash') }}"
  with_items: "{{ users }}"

- name: Ensure ssh folder for users
  file: >
    path="{{ '~' + item.name | expanduser }}/.ssh" state=directory
    owner="{{ item.name }}" group="{{ item.group }}" mode=go-rwx
  when: item.ssh_key is defined
  with_items: "{{ users }}"

- name: Ensure ssh key for users
  copy: >
    content="{{ item.ssh_key }}" dest="{{ '~' + item.name | expanduser }}/.ssh/id_rsa"
    owner="{{ item.name }}" group="{{ item.group }}" mode=go-rwx
  when: item.ssh_key is defined
  with_items: "{{ users }}"

- name: 'Adding public key for users'
  authorized_key: user="{{ item.name }}" key="{{ item.ssh_key }}" exclusive=true
  when: item.ssh_key is defined
  with_items: "{{ users }}"
  tags:
    - ssh
    - authorized_keys

- name: 'Adding users to sudo list'
  copy: dest="/etc/sudoers.d/{{ item.name }}" owner=root group=root mode="go-rwx" content="{{ item.name }} ALL=(ALL) ALL"
  when: item.sudo | default(False)
  with_items: "{{ users }}"

- name: 'Secure SSHD server'
  lineinfile:
    path: /etc/ssh/sshd_config
    backup: yes
    validate: "sshd -t -f %s"
    regexp: "^[#\\s]*{{item.split()|first}}\\s+.+"
    line: "{{item}}"
  with_items:
    - PasswordAuthentication no
    - PermitRootLogin prohibit-password
    - UseDNS no
  notify: Restart SSH
  tags:
    - ssh

- name: 'Locales'
  locale_gen: name={{ item }}
  with_items: "{{ locales }}"

- name: 'Ensure profiles'
  copy: dest="/etc/profile.d/{{ item.filename }}" content="{{ item.content }}"
  with_items:
    - filename: editor.sh
      content: |
        export EDITOR=vim
